
-include build/.config.mk
-include $(SHOTODOL_HOME)/Makefile.in

all:makeplugins shotodol

makeankhi:
	$(BUILD) -C ankhi/scale
	$(BUILD) -C ankhi/imgdiff
	$(BUILD) -C ankhi/convert
	$(BUILD) -C ankhi/imgtrix
	$(BUILD) -C ankhi/imgstruct
	$(BUILD) -C ankhi/cv
	$(BUILD) -C ankhi/edge
	$(BUILD) -C lang/token

cleanankhi:
	$(CLEAN) -C ankhi/scale
	$(CLEAN) -C ankhi/imgdiff
	$(CLEAN) -C ankhi/convert
	$(CLEAN) -C ankhi/imgtrix
	$(CLEAN) -C ankhi/imgstruct
	$(CLEAN) -C ankhi/cv
	$(CLEAN) -C ankhi/edge
	$(CLEAN) -C lang/token

makecore:
	$(BUILD) -C libs/fastedge
	$(BUILD) -C libs/opencv
	$(BUILD) -C libs/netpbm
	$(BUILD) -C libs/rawimg
	$(BUILD) -C libs/dryman_kmeans
	$(BUILD) -C libs/jpeg
	$(BUILD) -C transform/strtrans
	$(BUILD) -C libs/xmlparser

cleancore:
	$(CLEAN) -C libs/fastedge
	$(CLEAN) -C libs/opencv
	$(CLEAN) -C libs/netpbm
	$(CLEAN) -C libs/rawimg
	$(CLEAN) -C libs/dryman_kmeans
	$(CLEAN) -C libs/jpeg
	$(CLEAN) -C transform/strtrans
	$(CLEAN) -C libs/xmlparser

clean:cleancore cleanankhi

