
SHOTODOL_CORE_PATH=$(SHOTODOL_HOME)/core/
SHOTODOL_LIB_PATH=$(SHOTODOL_HOME)/libs/
PROJECT_LIB_PATH=$(PROJECT_HOME)/libs/
INCLUDES+=-I$(SHOTODOL_LIB_PATH)/str_arms/include
INCLUDES+=-I$(SHOTODOL_LIB_PATH)/iostream/include
INCLUDES+=-I$(SHOTODOL_LIB_PATH)/propeller/include
INCLUDES+=-I$(SHOTODOL_LIB_PATH)/make100/include
INCLUDES+=-I$(PROJECT_LIB_PATH)/fastedge/include
INCLUDES+=-I$(PROJECT_LIB_PATH)/netpbm/include
INCLUDES+=-I$(PROJECT_LIB_PATH)/dryman_kmeans/include
INCLUDES+=-I$(SHOTODOL_CORE_PATH)/base/include
INCLUDES+=-I$(SHOTODOL_CORE_PATH)/io/include
INCLUDES+=-I$(SHOTODOL_CORE_PATH)/commands/include
INCLUDES+=-Iinclude
