KERNELOPERATIONS_CSOURCES=$(wildcard $(PROJECT_HOME)/ankhi/kernel/vsrc/*.c)
KERNELOPERATIONS_VSOURCE_BASE=$(basename $(notdir $(KERNELOPERATIONS_CSOURCES)))
OBJECTS+=$(addprefix $(PROJECT_OBJDIR)/, $(addsuffix .o,$(KERNELOPERATIONS_VSOURCE_BASE)))
